# Generated by Django 4.0 on 2022-05-27 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0004_remove_manufacturer_ship'),
        ('ship', '0002_ship_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='manufacturer.manufacturer'),
        ),
    ]
