# Generated by Django 4.0 on 2022-05-27 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0005_alter_manufacturer_name'),
        ('ship', '0006_alter_ship_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='cargo_capacity',
            field=models.FloatField(verbose_name='Capacité de chargement'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='crew_capacity',
            field=models.IntegerField(verbose_name='Equipage minimum'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='empty_mass',
            field=models.FloatField(verbose_name='Masse à vide'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='height',
            field=models.FloatField(verbose_name='Hauteur'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='length',
            field=models.FloatField(verbose_name='Longueur'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='manufacturer.manufacturer', verbose_name='Constructeur'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ship.status', verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='width',
            field=models.FloatField(verbose_name='Largeur'),
        ),
    ]
