# Generated by Django 4.0 on 2022-05-27 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0008_ship_specie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='specie',
        ),
    ]
