# Generated by Django 4.0 on 2022-05-27 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0002_ship_slug'),
        ('manufacturer', '0002_manufacturer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='ship',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ship', to='ship.ship'),
            preserve_default=False,
        ),
    ]
