# Generated by Django 4.0 on 2022-05-27 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0002_species_slug'),
        ('manufacturer', '0005_alter_manufacturer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='spacie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='species.species', verbose_name='Espèce'),
            preserve_default=False,
        ),
    ]
