# Generated by Django 4.0 on 2022-05-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0006_manufacturer_spacie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='activities',
            field=models.CharField(max_length=100, verbose_name='Activité(s)'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='date_created',
            field=models.DateField(verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='founder',
            field=models.CharField(max_length=100, verbose_name='Fondateur'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='headquarters',
            field=models.CharField(max_length=100, verbose_name='Siege social'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='history',
            field=models.TextField(verbose_name='Histoire'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(upload_to='manufacturers/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='summary',
            field=models.TextField(verbose_name='Résumé'),
        ),
    ]
