# Generated by Django 4.0 on 2022-05-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
